import { randomUUID } from 'node:crypto';
import { createWriteStream } from 'node:fs';
import { mkdir, open, rename, rm, stat } from 'node:fs/promises';
import path from 'node:path';
import type { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import {
  ByteRange,
  InvalidObjectKeyError,
  ObjectInfo,
  ObjectNotFoundError,
  ObjectStorage,
  StoredObject,
} from './object-storage.js';

const BUCKET_NAME_REGEX = /^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$/;
const KEY_PART_REGEX = /^[A-Za-z0-9._-]+$/;

const CONTENT_TYPES: Record<string, string> = {
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
};

// Stores objects on disk as <rootDir>/<bucket>/<key>
export class LocalObjectStorage extends ObjectStorage {
  private readonly rootDir: string;

  constructor(rootDir: string) {
    super();
    this.rootDir = path.resolve(rootDir);
  }

  async putObject(bucket: string, key: string, body: Readable) {
    const filePath = this.getFilePath(bucket, key);
    await mkdir(path.dirname(filePath), { recursive: true });

    // Write to a temp file first and rename at the end. Rename is atomic,
    // so nobody can read a half written file.
    const tempPath = `${filePath}.${randomUUID()}.part`;
    try {
      await pipeline(body, createWriteStream(tempPath, { flags: 'wx' }));
      const { size } = await stat(tempPath);
      await rename(tempPath, filePath);
      return size;
    } catch (error) {
      await rm(tempPath, { force: true });
      throw error;
    }
  }

  async headObject(bucket: string, key: string): Promise<ObjectInfo | null> {
    try {
      const stats = await stat(this.getFilePath(bucket, key));
      if (!stats.isFile()) {
        return null;
      }
      return this.toObjectInfo(bucket, key, stats.size, stats.mtime);
    } catch (error) {
      if (isNotFoundError(error)) {
        return null;
      }
      throw error;
    }
  }

  async getObject(
    bucket: string,
    key: string,
    range?: ByteRange,
  ): Promise<StoredObject> {
    let file;
    try {
      file = await open(this.getFilePath(bucket, key), 'r');
    } catch (error) {
      if (isNotFoundError(error)) {
        throw new ObjectNotFoundError(bucket, key);
      }
      throw error;
    }

    const stats = await file.stat();
    const body = file.createReadStream({
      start: range?.start,
      end: range?.end,
    });

    return {
      ...this.toObjectInfo(bucket, key, stats.size, stats.mtime),
      body,
    };
  }

  async deleteObject(bucket: string, key: string) {
    await rm(this.getFilePath(bucket, key), { force: true });
  }

  // Keys are generated by us, but still make sure nothing like "../" can
  // point outside of the bucket folder.
  private getFilePath(bucket: string, key: string): string {
    if (!BUCKET_NAME_REGEX.test(bucket)) {
      throw new InvalidObjectKeyError(`${bucket}/${key}`);
    }

    const parts = key.split('/');
    const hasBadPart = parts.some(
      (part) => !KEY_PART_REGEX.test(part) || part === '.' || part === '..',
    );
    if (!key || key.length > 1024 || hasBadPart) {
      throw new InvalidObjectKeyError(key);
    }

    const bucketDir = path.join(this.rootDir, bucket);
    const filePath = path.join(bucketDir, ...parts);
    if (!filePath.startsWith(bucketDir + path.sep)) {
      throw new InvalidObjectKeyError(key);
    }
    return filePath;
  }

  private toObjectInfo(
    bucket: string,
    key: string,
    size: number,
    lastModified: Date,
  ): ObjectInfo {
    const extension = path.extname(key).toLowerCase();
    return {
      bucket,
      key,
      size,
      lastModified,
      contentType: CONTENT_TYPES[extension] ?? 'application/octet-stream',
      // weak etag from size + mtime, express does the same for static files
      etag: `W/"${size.toString(16)}-${lastModified.getTime().toString(16)}"`,
    };
  }
}

function isNotFoundError(error: unknown) {
  return (error as NodeJS.ErrnoException).code === 'ENOENT';
}
